Smth went wrong with comparison to  MGCAEGKAVAAAAPTELQTKGKNGDGRRRSAKDHHPGKTLPENPAGFTSTATADSRALLQAYIDGHSVVIFSRSTCTRCTEVKKLFKSLCVPYFVLELDQTEDGRALEGTLSELAAETDLPVVFVKQRKIGGHGPTLKAYQEGRLQKLLKMNGPEDLPKSYDYDLIIIGGGSGGLAAAKEAAQYGKKVMVLDFVTPTPLGTRWGLGGTCVNVGCIPKKLMHQAALLGQALQDSRNYGWKVEETVKHDWDRMIEAVQNHIGSLNWGYRVALREKKVVYENAYGQFIGPHRIKATNNKGKEKIYSAERFLIATGERPRYLGIPGDKEYCISSDDLFSLPYCPGKTLVVGASYVALECAGFLAGIGLDVTVMVRSILLRGFDQDMANKIGEHMEEHGIKFIRQFVPIKVEQIEAGTPGRLRVVAQSTNSEEIIEGEYNTVMLAIGRDACTRKIGLETVGVKINEKTGKIPVTDEEQTNVPYIYAIGDILEDKVELTPVAIQAGRLLAQRLYAGSTVKCDYENVPTTVFTPLEYGACGLSEEKAVEKFGEENIEVYHSYFWPLEWTIPSRDNNKCYAKIICNTKDNERVVGFHVLGPNAGEVTQGFAAALKCGLTKKQLDSTIGIHPVCAEVFTTLSVTKRSGASILQAGCUG
Smth went wrong with comparison to  MWRSLGLALALCLLPSGGTESQDQSSLCKQPPAWSIRDQDPMLNSNGSVTVVALLQASUYLCILQASKLEDLRVKLKKEGYSNISYIVVNHQGISSRLKYTHLKNKVSEHIPVYQQEENQTDVWTLLNGSKDDFLIYDRCGRLVYHLGLPFSFLTFPYVEEAIKIAYCEKKCGNCSLTTLKDEDFCKRVSLATVDKTVETPSPHYHHEHHHNHGHQHLGSSELSENQQPGAPNAPTHPAPPGLHHHHKHKGQHRQGHPENRDMPASEDLQDLQKKLCRKRCINQLLCKLPTDSELAPRSUCCHCRHLIFEKTGSAITUQCKENLPSLCSUQGLRAEENITESCQURLPPAAUQISQQLIPTEASASURUKNQAKKUEUPSN
Smth went wrong with comparison to  MPRQATSRLVVGEGEGSQGASGPAATMLRSLLLHSLRLCAQTASCLVLFPRFLGTAFMLWLLDFLCIRKHFLGRRRRGQPEPEVELNSEGEEVPPDDPPICVSDDNRLCTLASLKAVWHGQKLDFFKQAHEGGPAPNSEVVLPDGFQSQHILDYAQGNRPLVLNFGSCTUPPFMARMSAFQRLVTKYQRDVDFLIIYIEEAHPSDGWVTTDSPYIIPQHRSLEDRVSAARVLQQGAPGCALVLDTMANSSSSAYGAYFERLYVIQSGTIMYQGGRGPDGYQVSELRTWLERYDEQLHGARPRRV
652      652
1010    1010
654      654
1170    1170
1326    1326
Name: position_in_fasta, dtype: int64 652     1865.0
1010     465.0
654      459.5
1170     441.0
1326     436.5
Name: similarity, dtype: float64
                                          query  position_in_fasta  \
652   /home/anton_maximov/BACHELOR/P08069.fasta                652   
1010  /home/anton_maximov/BACHELOR/P08069.fasta               1010   
654   /home/anton_maximov/BACHELOR/P08069.fasta                654   
1170  /home/anton_maximov/BACHELOR/P08069.fasta               1170   
1326  /home/anton_maximov/BACHELOR/P08069.fasta               1326

      similarity  identity                                           sequence  \
652       1865.0       359  (M, I, L, N, S, S, T, E, D, G, I, K, R, I, Q, ...   
1010       465.0       162  (M, E, G, I, S, I, Y, T, S, D, N, Y, T, E, E, ...   
654        459.5       144  (M, A, S, S, W, P, P, L, E, L, Q, S, S, N, Q, ...   
1170       441.0       164  (M, E, T, N, S, S, L, P, T, N, I, S, G, G, T, ...   
1326       436.5       159  (M, S, N, I, T, D, P, Q, M, W, D, F, D, D, L, ...   

                                                 name  
652    lcl|BSEQ0009910|Type-1 angiotensin II receptor  
1010  lcl|BSEQ0001830|C-X-C chemokine receptor type 4  
654            lcl|BSEQ0013954|B1 bradykinin receptor  
1170            lcl|BSEQ0016276|fMet-Leu-Phe receptor  
1326  lcl|BSEQ0012470|C-X-C chemokine receptor type 1  
